name: Kaggle kernel actionsa

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.6.10' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }} 

    steps:
    - uses: actions/checkout@v2

    - name: Push kernel to kaggle
      uses: joel-hanson/kaggle-kernel-actions@master
      with:
        kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
        kaggle_key: ${{ secrets.KAGGLE_KEY }}
        kaggle_make_new_kernel: true
        kaggle_metadata_path: kernel-metadata.json
        kernel_id: pcbrown/project-vgsales4
        #competition: titanic
        dataset_sources: gregorut/videogamesales
